### ISSUE TITLE
Contact information on eclipse IDE still link to snapcrafters

### ISSUE THREAD

**Issue by alculete** [eclipse-linuxtools/eclipse-ide-snap#3]
![image](https://github.com/user-attachments/assets/85812b0e-dc3b-40d9-834e-a1204cccd37f)

**Comment by fredg02** [comment]
This has been fixed.

**Comment by alculete** [comment]
@fredg02  this link seems to go to the general ticket for the whole Eclipse Platform and it would be hard to find the right app to report to. Wouldn't be easier to link to [eclipse-ide-snap](https://github.com/eclipse-linuxtools/eclipse-ide-snap) or this is the standard for all apps?

**Comment by fredg02** [comment]
Your screenshot was referring to the contact field. I've changed that to point to https://github.com/eclipse-linuxtools/eclipse-ide-snap/issues.

> @fredg02 this link seems to go to the general ticket for the whole Eclipse Platform and it would be hard to find the right app to report to. Wouldn't be easier to link to [eclipse-ide-snap](https://github.com/eclipse-linuxtools/eclipse-ide-snap) or this is the standard for all apps?

In this comment, you are most likely referring to the "Report a bug" field. I have added the same URL for reporting eclipse-ide-snap related bugs there as well now.

**Comment by alculete** [comment]
great thanks. also not sure if you are aware. 2024-12 is not launching I have reported [here](https://github.com/eclipse-linuxtools/eclipse-ide-snap/issues/5)
