### ISSUE TITLE
unable to run Eclipse IDE after upgrade to 2024-12

### ISSUE THREAD

**Issue by alculete** [eclipse-linuxtools/eclipse-ide-snap#5]
unable to run Eclipse IDE after upgrade to 2024-12

![image](https://github.com/user-attachments/assets/a8f5ba59-38ba-4e4c-b29b-4f4f2509e55b)

**Comment by fredg02** [comment]
Please provide more information about your system. Does a fresh installation work? Does a non-snap version of Eclipse IDE 2024-12 work?

**Comment by alculete** [comment]
I was on 2024-09 and it works fine. this is only happening with version 2024-12.
I also tried a fresh install and the issue persists.
`$ sudo snap revert eclipse-ide `  is a workaround since it reverts to the previous version (2024-09)

**Comment by fredg02** [comment]
Please state your operating system (Windows, Mac, Linux) and OS version.

**Comment by alculete** [comment]
**OS:** Ubuntu oracular 24.10 x86_64
**Host:** Vostro 15 5510
**Kernel:** Linux 6.11.0-9-generic
**Shell:** bash 5.2.32
**Display (LGD06E0):** 1920x1080 @ 60 Hz in 15″ [Built-in]
**DE:** GNOME 47.0
**WM:** Mutter (Wayland)
**WM Theme:** Yaru
**Theme:** Yaru [GTK2/3/4]
**Icons:** Yaru [GTK2/3/4]
**Font:** Ubuntu Sans (11pt) [GTK2/3/4]
**Cursor:** Yaru (24px)
**Terminal:** GNOME Terminal 3.54.0

**CPU:** 11th Gen Intel(R) Core(TM) i7-11390H (8) @ 5.00 GHz
**GPU 1:** NVIDIA GeForce MX450
**GPU 2:** Intel Iris Xe Graphics @ 1.40 GHz [Integrated]
**Memory:** 12.13 GiB / 14.86 GiB (82%)
**Disk:** 5.16 GiB / 368.40 GiB (1%) - zfs
**Local IP (wlp0s20f3):** 192.168.0.5/24
**Battery (DELL MVK1126):** 100% [AC Connected]

**Comment by fredg02** [comment]
@Mailaender any idea where this issue comes from?

**Comment by Mailaender** [comment]
We were shipping a broken version initially but https://github.com/eclipse-linuxtools/eclipse-ide-snap/issues/1 was already fixed. Can you tell which version you have installed and which version you are resetting to? Like which snap revision?

**Comment by Mailaender** [comment]
Can't reproduce.
