### ISSUE TITLE
2024-12 arm incorrectly packaged

### ISSUE THREAD

**Issue by Guite** [eclipse-linuxtools/eclipse-ide-snap#6]
### What happened?

Yesterday I wanted to start eclipse but nothing happened. When I started it using CLI I got:

```
To override eclipse.ini, copy the default file to '/home/.../snap/eclipse/110/eclipse.ini' and modify to suit.
/snap/eclipse/110/bin/eclipse-wrapper: Zeile 9: /snap/eclipse/110/usr/lib/eclipse/eclipse: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei
```

After I did `snap refresh eclipse --channel latest/edge` it downgraded to 2024-09 and started again afterwards.

So I assume that 2024-12 is incorrectly packaged, because I am running an ARM machine (`aarch64` architecture) and the error message implies that it tried to start a x86 binary.

### What should have happened?

I expected Eclipse to start as usual.

### Output of `snap info $snap_name`

```shell
name:      eclipse
summary:   Extensible Tool Platform and Java IDE
publisher: Eclipse Foundation (eclipsefoundation✓)
store-url: https://snapcraft.io/eclipse
contact:   https://github.com/snapcrafters/eclipse/issues
license:   unset
description: |
  Eclipse provides IDEs and platforms for nearly every language and architecture. We are famous for
  our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible platforms for creating desktop,
  Web and cloud IDEs. These platforms deliver the most extensive collection of add-on tools
  available for software developers.
  
  You may need to install a compatible JRE on the host
  
     sudo apt install default-jre
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - eclipse
snap-id:      QzFGHW76hR3cZjpcuHt4sAjj5KZbd05T
tracking:     latest/stable
refresh-date: heute um 06:54 CET
channels:
  latest/stable:    2024-12 2024-12-03 (110) 367MB classic
  latest/candidate: 2024-09 2024-09-12 (100) 358MB classic
  latest/beta:      ↑                              
  latest/edge:      2024-09 2024-09-13 (102) 358MB classic
installed:          2024-12            (110) 367MB classic
```

### Output of `snap connections $snap_name`

```shell
nothing
```

### Output of `snap version`

```shell
snap    2.66.1+24.10
snapd   2.66.1+24.10
series  16
ubuntu  24.10
kernel  6.12.0-17-qcom-x1e
```

**Comment by Mailaender** [comment]
I am building the ARM version on x64 because we don't have Linux ARM GitHub runners for the moment. As nothing is really compiled but just repacked I thought this would work. The logs at https://github.com/eclipse-linuxtools/eclipse-ide-snap/actions/runs/12145366008/job/33866829890 are pretty useless and don't even mention the tarball downloaded.

**Comment by Mailaender** [comment]
Public GitHub hosted runners for ARM https://github.com/github/roadmap/issues/970 have been delayed until next year.

**Comment by Guite** [comment]
How was 2024-09 built (since this works like a charm)?

**Comment by Mailaender** [comment]
I think the @snapcrafters used Launchpad, which has native ARM runners. I will try to use an emulator for now.

**Comment by Guite** [comment]
Works - thanks for the quick reaction :+1:
