### ISSUE TITLE
Snap package for Eclipse Installer

### ISSUE THREAD

**Issue by thahnen** [eclipse-linuxtools/eclipse-ide-snap#8]
Hey everyone,

would it be possible to additionally create an official snap package for the Eclipse installer itself?
I'm not familiar with `snap` itself, but from the layout of the package, it should be as simple as copying the existing one and adjusting the paths to match the ones in the Eclipse installer directory structure?

Best,
Tobias

**Comment by Mailaender** [comment]
It might not be allowed to install files outside the sandbox at least not in the system directories. I guess it could be possible but then again what is the point. When it updates it won't automatically update the installed products. Out of scope here, but nothing stopping you.

**Comment by thahnen** [comment]
Thanks for the explanation, I wasn't fully aware of the limitations with the sandbox.
